### ISSUE TITLE
Let's make royalty % to be a variable that is settable by the owner

### ISSUE THREAD

**Issue by weiks** [weiks/quarter-sol#6]
Perhaps it should be an integer with 10**18 zeroes, so that we can have flexibility is resetting the royalty amount. The default at creation is 15%.

https://github.com/weiks/quarter-sol/blob/2ef9c5ce68c2e44dde87b684227693658f6c4505/contracts/Quarters.sol#L312

**Comment by NirajBhattarai** [comment]
I am closing this issue as we already fixed this
